name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        # No dependencies needed for static site
        echo "Static site - no dependencies to install"
        
    - name: Validate HTML
      run: |
        # Basic HTML validation
        if command -v tidy >/dev/null 2>&1; then
          tidy -q -e index.html
        else
          echo "HTML Tidy not available, skipping validation"
        fi
        
    - name: Check for broken links
      run: |
        # Install link checker
        npm install -g broken-link-checker
        
        # Check for broken internal links
        blc http://localhost:8000 -ro --exclude-external || true
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        exclude_assets: |
          qbacktester/
          .github/
          *.md
          .gitignore
          .gitattributes
